name: Code Compiler
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.6'
    - name: configure
      run: ./configure
    - name: install pip requirements
      run: pip install --quiet --no-cache-dir -r requirements.txt
    - name: make check
      run: make check
